### ISSUE TITLE
How remove the Feature.REGEX_BACKTRACKING_LIMIT

### ISSUE THREAD

**Issue by tboenig** [infotexture/dita-bootstrap.lunr#11]
Hello,

I would very much like to use the lunr solution.
But I get the following error message:
```
[INFO] Building project .github/dita-ot/html.xml
     [xslt] Regex backtracking limit exceeded processing ^[....]*([....]+?)[....]*$\Z. Simplify the regular expression, or set Feature.REGEX_BACKTRACKING_LIMIT to -1 to remove this limit.
     [xslt] Failed to transform document: Failed to transform document: Regex backtracking limit exceeded processing ^[....]*([....]+?)[....]*$\Z. Simplify the regular expression, or set Feature.REGEX_BACKTRACKING_LIMIT to -1 to remove this limit.
```

An index is also not built see:
https://github.com/tboenig/t_guidelines/blob/gh-pages/html/js/lunr-client.js

Here my project/repo:
https://github.com/tboenig/t_guidelines

I have already tried several things.
1. I assume there is a quantity problem (regex..)
2. Somewhere a parameter is not set correctly.

 Thank you.

**Comment by infotexture** [comment]
Danke Matthias, glad to hear you found this and are interested in using it.

We haven't published an official release yet as we're still polishing a few rough edges, but user feedback is the best way to improve something like this, so thanks for taking the time to report this issue.

I haven't seen this error so far, so I'm wondering if there's something peculiar to your project that triggers this. 🤔

**Comment by tboenig** [comment]
Thank you very much for the feedback.
I was looking for specifics. In the process, I may have found one:
```xml
<chapter href="trans/structur_gt.dita">
        <topicref href="structur_gt.ditamap" format="ditamap"/>
</chapter>
```
I add another ditamap to the ditamap. To the best of my understanding, this is DITA conforming.  I have now removed this feature. 
The warning "...Feature.REGEX_BACKTRACKING_LIMIT to -1..." is now no longer reported. But my chapter is missing.  :slightly_frowning_face: 

The search index is still not build.

When using: ```<publication transtype="html5">```
Also does not abort processing a ditamap with a ditamap recursion.

Thanks again.

**Comment by jason-fox** [comment]
It is always good to get another test case document set. The problematic regex in this case was the following line:

```diff
       <xsl:element name="text">
-        <xsl:value-of  select="replace(replace($TEXT , '^\s*(.+?)\s*$', '$1'), '^ .*$', '')" />
+        <xsl:value-of select="normalize-space($TEXT)"/>
       </xsl:element>
```

There were a couple of extra issues regarding stemming and stop words, but I've included a fix for those as well.

**Comment by jason-fox** [comment]
If you want to run the patch before it lands on `develop`, amend your action as follows:

```diff
        plugins: |
          https://github.com/jason-fox/fox.jason.extend.css/archive/master.zip
          https://github.com/infotexture/dita-bootstrap/archive/master.zip
+         https://github.com/jason-fox/dita-bootstrap.lunr/archive/feature/offline.zip
          https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
          fox.jason.favicon
```

**Comment by jason-fox** [comment]
You'll need https://github.com/infotexture/dita-bootstrap/archive/develop.zip then.

**Comment by tboenig** [comment]
puh,

the action workflow is running again.

- unfortunately, an index is not formed.
-- isn't my dita project too big?
- but the localization works now

**Comment by jason-fox** [comment]
If I manually copy over preview.json and search_index.json - it works properly https://jason-fox.github.io/t_guidelines/html/trans/ - this would seem to  indicate a fault in the GitHub Action.

**Comment by jason-fox** [comment]
I think that the underlying issue may be  reduced to a combination of running the `dita-ot/dita-ot-action` and creating a document in not in English For German to work, I think that the DE-DE locale needs to be  generated within the action:

```console
locale-gen de_DE.UTF-8 
LANG="de_DE.UTF-8"  
LANGUAGE="de_DE:de"  
LC_ALL="de_DE.UTF-8"

dita -f html5-bootstrap -i ...etc
```

The following GitHub Action is building your index successfully in German: https://github.com/jason-fox/t_guidelines/blob/main/.github/workflows/dita.yml -it is using the version found in PR #10 10
