### ISSUE TITLE
Search not working with OT 4.1.1?

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap.lunr#15]
Hi, 

Again: great project, looking forward to using this with DITA Bootstrap!

However, ever since I switched to DITA-OT 4.1.1, the Lunr search stopped working. The LUNR_DATA and PREVIEW_LOOKUP fields in the lunr-client.js file are empty, so basically the index is not being created at all. And naturally the search always finds nothing.

I noticed that this is also the case with the DITA Bootstrap site search, so I would assume this is just work in progress?

**Comment by jason-fox** [comment]
There is a fix  queued in PR #10

**Comment by jason-fox** [comment]
Now that I look in to it, it is working on 4.0.2 but not 4.1.1 - you can see a working project [here](https://github.com/jason-fox/dita-bootstrap/blob/feature/4.1.1/.github/workflows/ci.yml) 

```diff
  -  name: Build Bootstrap
-       uses: dita-ot/dita-ot-action@4.0.2
+       uses: dita-ot/dita-ot-action@4.1.1
 ```

Leaves the `preview.json` blank.

**Comment by jason-fox** [comment]
It looks like the XSLT processor has changed functionality:

```diff
<xsl:apply-templates 
-  select="document(document-uri(.))/topics/node()" 
+  select="./topics/node()"
    mode="data-output" />
```

I've altered  PR https://github.com/infotexture/dita-bootstrap.lunr/pull/10 to add a hacky workaround to  [here](https://github.com/infotexture/dita-bootstrap.lunr/blob/b3e9848f9ede33ece774fe1bed0683b66d031c31/xsl/merge-data.xsl#L67-#L77), but a better solution would be to have two releases of the lunr plugin to cope with both syntaxes or understand why the XSLT processor is now failing.

**Comment by jason-fox** [comment]
Modernized the merge function [here](https://github.com/infotexture/dita-bootstrap.lunr/blob/4c2269b11fb02a7c78632f45646b9f374e3dd928/xsl/merge-data.xsl#L64-L72) - now seems to work fine for 4.0 and 4.1

**Comment by lakokkonen** [comment]
Yes, now it's working with 4.1.
