### ISSUE TITLE
Offline search

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap.lunr#2]
From what I've seen in local testing, it looks like this currently requires an internet connection to work, as the Lunr script needs to be downloaded from https://unpkg.com/lunr/lunr.js, even though the output includes `html/js/lunr-client.js`.

The [docs](https://infotexture.github.io/dita-bootstrap/search-box.html) explain the need to specify `--lunr.search=WEBSITE_URL`, so it seems you need to know where the final output will be hosted when you generate the output.

To make the output self-contained and portable, I'm wondering if we could pre-generate the search index and ship the necessary JavaScript in the output folder, so the search would work in offline environments.

[Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/) currently ships Lunr this way, so there must be some way of generating the search index during the build process and bundling the index and JavaScript for offline use.

**Comment by jason-fox** [comment]
The search index already is pre-generated for efficiency, but shipping the  lunr.js JavaScript directly doesn't currently make sense, as this is a dependent add-on to the dita-bootstrap plugin and that already requires an internet connection to download Bootstrap

**Comment by infotexture** [comment]
> The search index already is pre-generated for efficiency

🎗️ Good to know. The MkDocs Lunr implementation includes a `search_index.json` file in the output folder, and since I didn't see anything like that here, I assumed the index was being  generated on the fly.

> the dita-bootstrap plugin […] already requires an internet connection to download Bootstrap

🤦 Ah, right. I was recalling an earlier version of the plug-in, which I had originally designed for offline use, so the Bootstrap CSS was bundled with the plug-in and did not require a network connection.

As later versions added JavaScript features, those embedded resources were replaced with external links in [`includes/bootstrap.hdf.xml`](https://github.com/infotexture/dita-bootstrap/blob/develop/includes/bootstrap.hdf.xml).

IIRC, that change was intended to work around issues with relative paths to bundled CSS files in earlier toolkit versions, and the lack of comparable parameters like `args.copycss` for bundled JavaScript resources.

So you're right: we'd need to solve the offline use case in the DITA Bootstrap plug-in before implementing it here.
